services:
  app:
    container_name: django-app-demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.10.5}
    image: django-app-demo:1.0.0
    restart: always
    ports:
      - "80:80"
    environment:
      - APP_DEBUG=${APP_DEBUG:-1}
      - APP_KEY=${APP_KEY:-secret}
      - DB_ENGINE=${DB_ENGINE:-django.db.backends.mysql}
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-django}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - $PWD:/usr/src/app
    depends_on:
      - database

  database:
    container_name: django-app-db-demo
    image: mariadb:${MARIADB_VERSION:-10.8.3}
    restart: always
    ports:
      - ${DOCKER_DB_HOST:-127.0.0.1:3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-django}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
