version: "3"

services:
  app:
    container_name: django-app-demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - NGINX_VERSION=${NGINX_VERSION}
    image: django_app_demo:1.0
    restart: always
    volumes:
      - $PWD:/usr/src/app
    depends_on:
      - database
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000

  database:
    container_name: django-app-db-demo
    image: mariadb:${MARIADB_VERSION}
    restart: always
    ports:
      - ${DOCKER_DB_HOST}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: django-app-nginx-demo
    image: nginx:${NGINX_VERSION}-alpine
    restart: always
    volumes:
      - $PWD:/usr/share/nginx/html
    ports:
      - ${DOCKER_HOST}:80
    depends_on:
      - app

volumes:
  db_data: