# Generated by Django 4.0.5 on 2022-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.FloatField()),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('colors', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
