apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-demo
  namespace: demos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
  selector:
    matchLabels:
      type: django-app-demo
